### ISSUE TITLE
error in running the sPARTA 

### ISSUE THREAD

**Issue by pokhrelsuresh** [atulkakrana/sPARTA.github#9] opened 2017-07-26 20:34 UTC
Hi Atul,

I was running sPARTA for target prediction using genome and .gff3 file from phytozome  and got an error:
Traceback (most recent call last):
  File "sPARTA.py", line 2921, in <module>
    main()
  File "sPARTA.py", line 2609, in main
    coords                            = extractFeatures(args.genomeFile,chromoDict,chromoLenDict,genome_info,genome_info_inter) ## Extracts Coords from GFF3
  File "sPARTA.py", line 650, in extractFeatures
    genome_info_inter.append((gene1[0],gene1[1],inter_name,inter_start,inter_end,gene_type)) ##Chr_id, strand
UnboundLocalError: local variable 'inter_end' referenced before assignment

I was using the latest version of sPARTA.  Any help would be appreciated.

Thanks,
Suresh

**Comment by atulkakrana** [comment] 2017-07-27 01:27
Thank you reporting the issues. Could you please tell us which genome you were using so that we can reproduce the error? 

Thanks

Atul

**Comment by atulkakrana** [comment] 2017-07-29 16:18
Suresh,

I tested on coffee genome and GFF3 file from Phytozome and sPARTA (v1.25) worked just fine. Did you used the latest sPARTA version? if yes, then tell me the species that you got error with.

Atul

**Comment by atulkakrana** [comment] 2017-07-31 19:09
Closing this report as issue couldn't be reproduced due to lack of information.

**Comment by pokhrelsuresh** [comment] 2017-08-02 15:50
Hi Atul,
Sorry for being late, the genome and gff file are of Flax (Linum usitatissimum v1.0) and the sPARTA version is 1.25. I tried older version also, for genic region older version of sPARTA works, but intergenic region both old and new version of sPARTA doesn't work and give above mentioned error for this species. Thank you for your help.
Suresh

**Comment by atulkakrana** [comment] 2017-08-03 21:31
I couldn't find the genome on Phytozome. It's hard to help you because you do not provide complete information. 

Atul

**Comment by pokhrelsuresh** [comment] 2017-08-03 22:01
http://genome.jgi.doe.gov/pages/dynamicOrganismDownload.jsf?organism=Lusitatissimum 

the above mentioned is the link for genome.

Suresh

**Comment by atulkakrana** [comment] 2017-08-03 22:32
> http://genome.jgi.doe.gov/pages/dynamicOrganismDownload.jsf?organism=Lusitatissimum
> 
> the above mentioned is the link for genome

But I couldn't find genome FASTA there:
<img width="1212" alt="screen shot 2017-08-03 at 6 31 46 pm" src="https://user-images.githubusercontent.com/6272752/28946740-1e898b8c-787a-11e7-8569-30de3165a025.png">

Atul

**Comment by pokhrelsuresh** [comment] 2017-08-03 23:00
Can you please click on the assembly pointer (the black one in your screenshot, you will see the genome.

**Comment by pokhrelsuresh** [comment] 2017-08-03 23:02
![image](https://user-images.githubusercontent.com/13205151/28947504-dd421076-7875-11e7-8113-30c312c80de9.png)

**Comment by pokhrelsuresh** [comment] 2017-08-15 20:29
Hi Atul,

I assume you are really busy, but just curious to check in whether you got chance to get the genome of Flax and working on the problem of gff file while running the sparta. Thank you for your help.

Suresh

**Comment by atulkakrana** [comment] 2017-08-19 20:35
Suresh,

Please download the new version from [here](https://github.com/atulkakrana/sPARTA). This is yet unreleased version. Let me know if the problem still persists. Thank you for your patience and reporting the issue.

Atul

**Comment by pokhrelsuresh** [comment] 2017-08-23 17:20
Hi Atul,
Thank you for the updated script. It works.

Suresh

**Comment by atulkakrana** [comment] 2017-08-23 19:48
Marking this issue as resolved - The updates will be added to next release.

**Closed as completed by atulkakrana** 2017-08-23 19:48 UTC
